vim.g.mapleader = '\\'

local opt = vim.opt

opt.autoindent = true
opt.autoread = true
opt.clipboard = "unnamed"
opt.expandtab = true
opt.foldenable = false
opt.ignorecase = true
opt.joinspaces = false
opt.laststatus = 3
opt.lazyredraw = true
opt.list = true
opt.listchars = "extends:❯,nbsp:~,precedes:❮,tab:▸ ,trail:⋅"
opt.number = true
opt.relativenumber = true
opt.shell = "/bin/bash"
opt.shiftwidth = 0
opt.showmode = false
opt.smartcase = true
opt.softtabstop = 4
opt.splitbelow = true
opt.splitright = true
opt.tabstop = 4
opt.textwidth = 80
opt.timeout = false
opt.undolevels = 1000
opt.virtualedit = "all"
