#!/usr/bin/env bash

export DISPLAY=localhost:0.0

export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

# XXX: Ruby doesn't like having /mnt/c (from WSL) in PATH because the
# permissions appear to be 777 even though they're really not. So, make aliases
# for commands we want to reach in Windows land.
# export PATH=$PATH:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/System32/Wbem:/mnt/c/windows/System32/WindowsPowerShell/v1.0/:/mnt/c/windows/System32/OpenSSH/:/mnt/c/Program\ Files\ (x86)/NVIDIA\ Corporation/PhysX/Common:/mnt/c/Program\ Files/NVIDIA\ Corporation/NVIDIA\ NvDLISR:/mnt/c/Program\ Files/Git/cmd:/mnt/c/Users/Pete/AppData/Local/Microsoft/WindowsApps:/mnt/c/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Vim\ 8.1:/mnt/c/Program\ Files\ (x86)/Vim/vim81:/mnt/c/Users/Pete/AppData/Local/Programs/Microsoft\ VS\ Code/bin:/snap/bin:~/IntelliJ/idea-IC-192.6817.14/bin:~/PyCharm/pycharm-community-2019.2.3/bin
export PATH=$PATH:/snap/bin:~/IntelliJ/idea-IC-192.6817.14/bin:~/PyCharm/pycharm-community-2019.2.3/bin:/usr/libexec/java_home:~/.nodenv/bin:~/.pyenv/bin:~/.rbenv/bin

alias code="/mnt/c/Users/Pete/AppData/Local/Programs/Microsoft\ VS\ Code/bin/code"

if command -v nodenv 1>/dev/null 2>&1; then
    eval "$(nodenv init -)"
fi

if command -v rbenv 1>/dev/null 2>&1; then
    eval "$(rbenv init -)"
fi

if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init -)"
fi

if [ -s ~/.keychain/$(hostname)-sh ]; then
    source ~/.keychain/$(hostname)-sh;
fi

