#!/usr/bin/env bash

set -Eeuxo pipefail

PWD=$(pwd)

rm -f ~/.bash_profile
ln -s ${PWD}/bash_profile ~/.bash_profile
rm -f ~/.bashrc
ln -s ${PWD}/bashrc ~/.bashrc
rm -f ~/.ctags
ln -s ${PWD}/ctags ~/.ctags
rm -f ~/.editrc
ln -s ${PWD}/editrc ~/.editrc
rm -f ~/.gitconfig
ln -s ${PWD}/gitconfig ~/.gitconfig
rm -f ~/.gitignore
ln -s ${PWD}/gitignore ~/.gitignore
rm -f ~/.inputrc
ln -s ${PWD}/inputrc ~/.inputrc
mkdir -p ~/.config
rm -f ~/.config/nvim
ln -s ${PWD}/nvim ~/.config/nvim
rm -f ~/.tmux.conf
ln -s ${PWD}/tmux.conf ~/.tmux.conf
rm -f ~/.vimrc
ln -s ${PWD}/vimrc ~/.vimrc
