#!/usr/bin/env bash

set -Eeuxo pipefail

PWD=$(pwd)

rm -f ~/.bash_profile
rm -f ~/.bashrc
rm -f ~/.config/nvim
rm -f ~/.ctags
rm -f ~/.editrc
rm -f ~/.gitconfig
rm -f ~/.gitignore
rm -f ~/.inputrc
rm -f ~/.tmux.conf
rm -f ~/.vimrc
rm -rf ~/.tmux/plugins/tpm

mkdir -p ~/.config 
mkdir -p ~/.tmux/plugins

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

ln -s "${PWD}/bash_profile" ~/.bash_profile
ln -s "${PWD}/bashrc" ~/.bashrc
ln -s "${PWD}/ctags" ~/.ctags
ln -s "${PWD}/editrc" ~/.editrc
ln -s "${PWD}/gitconfig" ~/.gitconfig
ln -s "${PWD}/gitignore" ~/.gitignore
ln -s "${PWD}/inputrc" ~/.inputrc
ln -s "${PWD}/nvim" ~/.config/nvim
ln -s "${PWD}/tmux.conf" ~/.tmux.conf
ln -s "${PWD}/vimrc" ~/.vimrc
